import Head from 'next/head';
import Banner from './components/Banner';
import CallToAction from './components/CallToAction';
import Entries from './components/Entries';

export default function Home() {
  return (
    <div className='home-container'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Banner />
      <CallToAction />
    </div>
  );
}
